spring.application.name=article-service

spring.datasource.url=jdbc:mysql://localhost:3306/webzine
spring.datasource.username=webzine_admin
spring.datasource.password=*whitejeans03
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

server.port=8081

mybatis.mapper-locations=classpath:mapper/**/*.xml
